### ISSUE TITLE
Global Unpaid Penalties

### ISSUE THREAD

**Issue by jkoritzinsky** [BROKE-KSP/BROKE#10]
We talked earlier about having global penalties for unpaid invoices.  What are we going to do, and are we going to scale it by number of unpaid invoices (and how)?

Current ideas:
- Reputation

Any others?

**Comment by magico13** [comment]
For scaling it might make sense to scale it based on the total funds unpaid, so small invoices will have a small penalty.

Reputation seems like the best thing for this, but alternatively just applying "late fees" might work.

Alternatively we could forgoe global penalties and leave that to individual FMs to handle.

**Comment by jkoritzinsky** [comment]
Let's just forgo global penalties.  I'm adding a reputation loss to unpaid loans in addition to late fees since Reputation is acting something like a credit score (loan templates enable/disable based off reputation and kerbucks at issuing time). We already have the penalty for crew, so I don't think we need another one.
