### ISSUE TITLE
When to send OnInvoiceUnpaid?

### ISSUE THREAD

**Issue by jkoritzinsky** [BROKE-KSP/BROKE#2]
Right now I have it sending if an invoice is unpaid upon clicking "Pay", but I think I want to change that.  I've got a few ideas on when it should fire:
- Start of next quarter
- A configurable amount of days after the invoice is sent
- The current design (I'm really not a big fan of this one.)

What do you think?

**Comment by johnqevil** [comment]
I think a configurable time period after it's sent would work nicely. Thinking of billable accounts, they're usually a net 30/60/90, due a certain amount of time after it's sent out to give the recipient time to pay it.

30 days would be pretty good as a default, just enough time to get some cash together to pay what's left.

**Comment by jkoritzinsky** [comment]
I was thinking 30 as well.

**Comment by magico13** [comment]
I personally prefer sticking just to quarters and years. If a new quarter rolls around you have to have paid off the previous one. Maybe even give them the chance to pay things off prior to the new quarter's revenue coming in (edit: and them facing penalties).

Otherwise, why not make it be the option of the IFundingModifier? Then they can decide whether it should be a specific number of days, but also provide options for year and quarter (should BROKE define the quarter and year as read-only values somewhere to make that easier?)

**Comment by johnqevil** [comment]
That makes sense too, that's how Kerbanomics had it a originally. This does bring up another question: should the penalties for not paying be a global setting, or FM based?

**Comment by magico13** [comment]
Depends on the penalty. Blanket reputation losses should probably be global (assuming we're taking away reputation if things are unpaid, we should discuss that), with any extra penalties being FM based (such as making kerbals quit or shutting down a mission, etc).

**Comment by jkoritzinsky** [comment]
One thing we could also do is make it tied to an InvoiceItem (at least internally).  We could add it to the data in there, and each day/quarter/year call a method on it to tell it to possibly send the unpaid message depending on its configuration.  That way we can have it be a global setting for some, and FM based for others (or a combination of the two).

**Comment by jkoritzinsky** [comment]
With the commit I just pushed I changed it to notify of missed payment when the next quarter is processed. Players will have the full quarter after they are first charged to pay without any penalty.  Afterwards, the InvoiceItems are told to notify their Modifiers of the missed payment at the start of each quarter until they are paid off.

**Comment by jkoritzinsky** [comment]
I'm going to close this since we haven't had any further discussion/issues about having it at the start of the following quarter.
