### ISSUE TITLE
Invoices no longer being sent

### ISSUE THREAD

**Issue by johnqevil** [BROKE-KSP/BROKE#3]
I haven't dug into this yet, but no FMs are triggering on either quarterly or yearly intervals since the last BROKE commit.

**Comment by jkoritzinsky** [comment]
This project with just the example still works on my system. Check the debug log. Sometimes there are some type conflicts between different assembly versions that causes just enough exceptions to break everything.

**Comment by johnqevil** [comment]
Ok, just rebuilt BROKE and the example FM from scratch, and that one is triggering just fine on quarterly right now.

I'll compare changes and see what's breaking Funding and Payroll.

**Comment by magico13** [comment]
Don't forget that the [build server](http://magico13.net:8080/) is always up to date with GitHub. I've got it set up so the BROKE_Defaults get built any time BROKE is updated, using the new .dll from BROKE.

**Comment by johnqevil** [comment]
I keep forgetting you have a build server at all. Bookmarking it this time,
thanks!

**Comment by magico13** [comment]
It's just my server sitting on my desk at home, so nothing fancy, but after some incorrect packaging of StageRecovery updates I decided I should no longer be allowed to package updates manually.

**Comment by johnqevil** [comment]
Looks like it is working now, had to clean the BROKE_Defaults bin folder
out in VS altogether.
