### ISSUE TITLE
Automatic Payment

### ISSUE THREAD

**Issue by magico13** [BROKE-KSP/BROKE#6]
We should provide several options for automatic payments.
- None: As it is now where you must click the "pay" button to pay any Invoices
- Partial: How I implemented it initially. Any debts are pulled out of any incoming revenue. If debts > revenue, the player must pay the rest manually. If debts < revenue, the player has paid all their debts and only receives revenue-debts in payment.
- Full: The balance of revenue-debt is taken from the player's account automatically, but not if the player's funds are below some minimal safety margin.

With all of these I think revenue should be paid to the player automatically. Alternatively that can be a separate setting, but then we should provide a "collect" button to cash in the revenues without having to pay off the debts at the same time.

**Comment by jkoritzinsky** [comment]
I think instead of all versions auto-collecting (since no one will be able to see where the income is coming from unless they look in the still unimplemented history), we should have 4 automatic payment options, the 3 listed above and an additional one:
- Auto-Collect: Incoming revenue is collected, and debts are left unpaid.

**Comment by magico13** [comment]
Regarding history, we should implement a minimal version of it such that when you open the GUI manually you see all of the Invoices that were reported last Quarter, instead of only the active Invoices. Basically, even after collection the Invoices should remain in the list for a Quarter.

I mention that here because that would solve the issue of not knowing what funds you've received and would then allow for automatic collection.

**Comment by jkoritzinsky** [comment]
The main issue I have with always-on automatic collection is that the "Revenue" section of the current quarter UI will always be empty because everything there is always auto-collected.

**Comment by magico13** [comment]
Hence my request to not make those disappear upon collection, that way that part isn't empty.

I think when you open the window you should see the last quarter, always, even after collecting revenue and paying off debts. This borders on the History aspect, so it might better be discussed there, but that would avert any loss of information due to automatic collection or automatic debt payment.
