### ISSUE TITLE
KSP 1.0.5 Status

### ISSUE THREAD

**Issue by magico13** [BROKE-KSP/BROKE#8]
Has anyone gotten a chance to take a look at if this is working in 1.0.5 yet? Realistically I expect we'll need a recompile. At best it works as-is, but my other mods needed a recompile.

Now that 1.0.5 has dropped, I'll likely be far more active, but will be prioritizing updates to my other mods first.

E: No errors on recompile. Haven't tested in-game.

**Comment by jkoritzinsky** [comment]
People have said that it works so I'm closing this.
