### ISSUE TITLE
Possible time calculation bug

### ISSUE THREAD

**Issue by jkoritzinsky** [BROKE-KSP/BROKE#9]
I'm working on the payment history (#7) and I noticed that our time calculation code will start to act wonky if someone plays a game longer than [233.4 Kerbin years](http://www.wolframalpha.com/input/?i=%282%5E31-1%29+seconds+%2F+9201600+seconds) because we are using 32-bit integers for our time checks. Do we want to switch our time code to 64-bit (`long`) so we won't have a problem unless someone plays longer than [1 trillion Kerbin years](http://www.wolframalpha.com/input/?i=%282%5E63-1%29+seconds+%2F+9201600+seconds)?

**Comment by magico13** [comment]
Definitely a good idea. I can't think of a good reason not to make that switch. If anyone has a game that runs for 1 trillion years then I think they've got other problems to deal with.
